declare const _default: {
    reset: string;
    bright: string;
    dim: string;
    underline: string;
    blink: string;
    reverse: string;
    hidden: string;
    txt: {
        dRed: string;
        dGreen: string;
        dYellow: string;
        dBlue: string;
        dMagenta: string;
        dCyan: string;
        red: string;
        green: string;
        yellow: string;
        blue: string;
        magenta: string;
        cyan: string;
        lRed: string;
        lGreen: string;
        lYellow: string;
        lBlue: string;
        lMagenta: string;
        lCyan: string;
        white: string;
        lGrey: string;
        grey: string;
        dGrey: string;
        black: string;
    };
    bg: {
        red: string;
        green: string;
        yellow: string;
        blue: string;
        magenta: string;
        cyan: string;
        white: string;
        black: string;
    };
    noBleed: (input: string) => string;
};
export = _default;
